// <auto-generated />
namespace MVC_CodeFirst_StoreProcedure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class YazarTableAddColumnAciklama3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YazarTableAddColumnAciklama3));
        
        string IMigrationMetadata.Id
        {
            get { return "202304100618337_YazarTableAddColumnAciklama3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
